apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: booking
          image: devopszms2024/zms-devops-booking-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          envFrom:
            - secretRef:
                name: mongodb-booking-secret
            - configMapRef:
                name: booking-configmap
            - configMapRef:
                name: mongodb-booking-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: booking
  namespace: backend
spec:
  selector:
    app: booking
  ports:
    - protocol: TCP
      name: http
      port: 8086
      targetPort: 8086
    - protocol: TCP
      name: grpc
      port: 8001
      targetPort: 8001