// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: booking_service.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccommodationHasReservationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId string `protobuf:"bytes,1,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
}

func (x *CheckAccommodationHasReservationRequest) Reset() {
	*x = CheckAccommodationHasReservationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAccommodationHasReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccommodationHasReservationRequest) ProtoMessage() {}

func (x *CheckAccommodationHasReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccommodationHasReservationRequest.ProtoReflect.Descriptor instead.
func (*CheckAccommodationHasReservationRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccommodationHasReservationRequest) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

type CheckAccommodationHasReservationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CheckAccommodationHasReservationResponse) Reset() {
	*x = CheckAccommodationHasReservationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAccommodationHasReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccommodationHasReservationResponse) ProtoMessage() {}

func (x *CheckAccommodationHasReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccommodationHasReservationResponse.ProtoReflect.Descriptor instead.
func (*CheckAccommodationHasReservationResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccommodationHasReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckGuestHasReservationForHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewerId string `protobuf:"bytes,1,opt,name=reviewerId,proto3" json:"reviewerId,omitempty"`
	HostId     string `protobuf:"bytes,2,opt,name=hostId,proto3" json:"hostId,omitempty"`
}

func (x *CheckGuestHasReservationForHostRequest) Reset() {
	*x = CheckGuestHasReservationForHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckGuestHasReservationForHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGuestHasReservationForHostRequest) ProtoMessage() {}

func (x *CheckGuestHasReservationForHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGuestHasReservationForHostRequest.ProtoReflect.Descriptor instead.
func (*CheckGuestHasReservationForHostRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckGuestHasReservationForHostRequest) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *CheckGuestHasReservationForHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CheckGuestHasReservationForHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasReservation bool `protobuf:"varint,1,opt,name=hasReservation,proto3" json:"hasReservation,omitempty"`
}

func (x *CheckGuestHasReservationForHostResponse) Reset() {
	*x = CheckGuestHasReservationForHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckGuestHasReservationForHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGuestHasReservationForHostResponse) ProtoMessage() {}

func (x *CheckGuestHasReservationForHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGuestHasReservationForHostResponse.ProtoReflect.Descriptor instead.
func (*CheckGuestHasReservationForHostResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckGuestHasReservationForHostResponse) GetHasReservation() bool {
	if x != nil {
		return x.HasReservation
	}
	return false
}

type CheckGuestHasReservationForAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasReservation bool `protobuf:"varint,1,opt,name=hasReservation,proto3" json:"hasReservation,omitempty"`
}

func (x *CheckGuestHasReservationForAccommodationResponse) Reset() {
	*x = CheckGuestHasReservationForAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckGuestHasReservationForAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGuestHasReservationForAccommodationResponse) ProtoMessage() {}

func (x *CheckGuestHasReservationForAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGuestHasReservationForAccommodationResponse.ProtoReflect.Descriptor instead.
func (*CheckGuestHasReservationForAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckGuestHasReservationForAccommodationResponse) GetHasReservation() bool {
	if x != nil {
		return x.HasReservation
	}
	return false
}

type CheckGuestHasReservationForAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewerId      string `protobuf:"bytes,1,opt,name=reviewerId,proto3" json:"reviewerId,omitempty"`
	AccommodationId string `protobuf:"bytes,2,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
}

func (x *CheckGuestHasReservationForAccommodationRequest) Reset() {
	*x = CheckGuestHasReservationForAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckGuestHasReservationForAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGuestHasReservationForAccommodationRequest) ProtoMessage() {}

func (x *CheckGuestHasReservationForAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGuestHasReservationForAccommodationRequest.ProtoReflect.Descriptor instead.
func (*CheckGuestHasReservationForAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckGuestHasReservationForAccommodationRequest) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *CheckGuestHasReservationForAccommodationRequest) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

type EditAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccommodationName string `protobuf:"bytes,2,opt,name=accommodation_name,json=accommodationName,proto3" json:"accommodation_name,omitempty"`
	Automatically     bool   `protobuf:"varint,3,opt,name=automatically,proto3" json:"automatically,omitempty"`
	HostId            string `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *EditAccommodationRequest) Reset() {
	*x = EditAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAccommodationRequest) ProtoMessage() {}

func (x *EditAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAccommodationRequest.ProtoReflect.Descriptor instead.
func (*EditAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{6}
}

func (x *EditAccommodationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditAccommodationRequest) GetAccommodationName() string {
	if x != nil {
		return x.AccommodationName
	}
	return ""
}

func (x *EditAccommodationRequest) GetAutomatically() bool {
	if x != nil {
		return x.Automatically
	}
	return false
}

func (x *EditAccommodationRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type EditAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditAccommodationResponse) Reset() {
	*x = EditAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAccommodationResponse) ProtoMessage() {}

func (x *EditAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAccommodationResponse.ProtoReflect.Descriptor instead.
func (*EditAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{7}
}

type CheckDeleteHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId string `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *CheckDeleteHostRequest) Reset() {
	*x = CheckDeleteHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDeleteHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeleteHostRequest) ProtoMessage() {}

func (x *CheckDeleteHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeleteHostRequest.ProtoReflect.Descriptor instead.
func (*CheckDeleteHostRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{8}
}

func (x *CheckDeleteHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CheckDeleteHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CheckDeleteHostResponse) Reset() {
	*x = CheckDeleteHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDeleteHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeleteHostResponse) ProtoMessage() {}

func (x *CheckDeleteHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeleteHostResponse.ProtoReflect.Descriptor instead.
func (*CheckDeleteHostResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{9}
}

func (x *CheckDeleteHostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckDeleteClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId string `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *CheckDeleteClientRequest) Reset() {
	*x = CheckDeleteClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeleteClientRequest) ProtoMessage() {}

func (x *CheckDeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeleteClientRequest.ProtoReflect.Descriptor instead.
func (*CheckDeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{10}
}

func (x *CheckDeleteClientRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type CheckDeleteClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CheckDeleteClientResponse) Reset() {
	*x = CheckDeleteClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeleteClientResponse) ProtoMessage() {}

func (x *CheckDeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeleteClientResponse.ProtoReflect.Descriptor instead.
func (*CheckDeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{11}
}

func (x *CheckDeleteClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddUnavailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccommodationName string `protobuf:"bytes,2,opt,name=accommodation_name,json=accommodationName,proto3" json:"accommodation_name,omitempty"`
	Automatically     bool   `protobuf:"varint,3,opt,name=automatically,proto3" json:"automatically,omitempty"`
	HostId            string `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *AddUnavailabilityRequest) Reset() {
	*x = AddUnavailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUnavailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUnavailabilityRequest) ProtoMessage() {}

func (x *AddUnavailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUnavailabilityRequest.ProtoReflect.Descriptor instead.
func (*AddUnavailabilityRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddUnavailabilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddUnavailabilityRequest) GetAccommodationName() string {
	if x != nil {
		return x.AccommodationName
	}
	return ""
}

func (x *AddUnavailabilityRequest) GetAutomatically() bool {
	if x != nil {
		return x.Automatically
	}
	return false
}

func (x *AddUnavailabilityRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type AddUnavailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddUnavailabilityResponse) Reset() {
	*x = AddUnavailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUnavailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUnavailabilityResponse) ProtoMessage() {}

func (x *AddUnavailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUnavailabilityResponse.ProtoReflect.Descriptor instead.
func (*AddUnavailabilityResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{13}
}

type FilterAvailableAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationIds []string `protobuf:"bytes,1,rep,name=accommodationIds,proto3" json:"accommodationIds,omitempty"`
	StartDate        string   `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate          string   `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *FilterAvailableAccommodationRequest) Reset() {
	*x = FilterAvailableAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterAvailableAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAvailableAccommodationRequest) ProtoMessage() {}

func (x *FilterAvailableAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAvailableAccommodationRequest.ProtoReflect.Descriptor instead.
func (*FilterAvailableAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{14}
}

func (x *FilterAvailableAccommodationRequest) GetAccommodationIds() []string {
	if x != nil {
		return x.AccommodationIds
	}
	return nil
}

func (x *FilterAvailableAccommodationRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *FilterAvailableAccommodationRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type FilterAvailableAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationIds []string `protobuf:"bytes,1,rep,name=accommodationIds,proto3" json:"accommodationIds,omitempty"`
}

func (x *FilterAvailableAccommodationResponse) Reset() {
	*x = FilterAvailableAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterAvailableAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAvailableAccommodationResponse) ProtoMessage() {}

func (x *FilterAvailableAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAvailableAccommodationResponse.ProtoReflect.Descriptor instead.
func (*FilterAvailableAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{15}
}

func (x *FilterAvailableAccommodationResponse) GetAccommodationIds() []string {
	if x != nil {
		return x.AccommodationIds
	}
	return nil
}

var File_booking_service_proto protoreflect.FileDescriptor

var file_booking_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x22, 0x53, 0x0a, 0x27, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x61,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x28, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x60, 0x0a, 0x26, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x51, 0x0a,
	0x27, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x61, 0x73, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0e, 0x68, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x5a, 0x0a, 0x30, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61,
	0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68, 0x61,
	0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7b, 0x0a, 0x2f,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x98, 0x01, 0x0a, 0x18, 0x45, 0x64,
	0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x75,
	0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x45, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x31, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x18, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x35,
	0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x22, 0x1b, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x89, 0x01,
	0x0a, 0x23, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x10, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x52, 0x0a, 0x24, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x61, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x32, 0xba, 0x07,
	0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5c, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c,
	0x0a, 0x11, 0x45, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x45, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7d, 0x0a, 0x1c,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0f, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x1f,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x86, 0x01, 0x0a, 0x1f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x2f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0xa1, 0x01, 0x0a, 0x28, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x39, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x89,
	0x01, 0x0a, 0x20, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x30, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x61, 0x73, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_booking_service_proto_rawDescOnce sync.Once
	file_booking_service_proto_rawDescData = file_booking_service_proto_rawDesc
)

func file_booking_service_proto_rawDescGZIP() []byte {
	file_booking_service_proto_rawDescOnce.Do(func() {
		file_booking_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_booking_service_proto_rawDescData)
	})
	return file_booking_service_proto_rawDescData
}

var file_booking_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_booking_service_proto_goTypes = []interface{}{
	(*CheckAccommodationHasReservationRequest)(nil),          // 0: booking.CheckAccommodationHasReservationRequest
	(*CheckAccommodationHasReservationResponse)(nil),         // 1: booking.CheckAccommodationHasReservationResponse
	(*CheckGuestHasReservationForHostRequest)(nil),           // 2: booking.CheckGuestHasReservationForHostRequest
	(*CheckGuestHasReservationForHostResponse)(nil),          // 3: booking.CheckGuestHasReservationForHostResponse
	(*CheckGuestHasReservationForAccommodationResponse)(nil), // 4: booking.CheckGuestHasReservationForAccommodationResponse
	(*CheckGuestHasReservationForAccommodationRequest)(nil),  // 5: booking.CheckGuestHasReservationForAccommodationRequest
	(*EditAccommodationRequest)(nil),                         // 6: booking.EditAccommodationRequest
	(*EditAccommodationResponse)(nil),                        // 7: booking.EditAccommodationResponse
	(*CheckDeleteHostRequest)(nil),                           // 8: booking.CheckDeleteHostRequest
	(*CheckDeleteHostResponse)(nil),                          // 9: booking.CheckDeleteHostResponse
	(*CheckDeleteClientRequest)(nil),                         // 10: booking.CheckDeleteClientRequest
	(*CheckDeleteClientResponse)(nil),                        // 11: booking.CheckDeleteClientResponse
	(*AddUnavailabilityRequest)(nil),                         // 12: booking.AddUnavailabilityRequest
	(*AddUnavailabilityResponse)(nil),                        // 13: booking.AddUnavailabilityResponse
	(*FilterAvailableAccommodationRequest)(nil),              // 14: booking.FilterAvailableAccommodationRequest
	(*FilterAvailableAccommodationResponse)(nil),             // 15: booking.FilterAvailableAccommodationResponse
}
var file_booking_service_proto_depIdxs = []int32{
	12, // 0: booking.BookingService.AddUnavailability:input_type -> booking.AddUnavailabilityRequest
	6,  // 1: booking.BookingService.EditAccommodation:input_type -> booking.EditAccommodationRequest
	14, // 2: booking.BookingService.FilterAvailableAccommodation:input_type -> booking.FilterAvailableAccommodationRequest
	8,  // 3: booking.BookingService.CheckDeleteHost:input_type -> booking.CheckDeleteHostRequest
	10, // 4: booking.BookingService.CheckDeleteClient:input_type -> booking.CheckDeleteClientRequest
	2,  // 5: booking.BookingService.CheckGuestHasReservationForHost:input_type -> booking.CheckGuestHasReservationForHostRequest
	5,  // 6: booking.BookingService.CheckGuestHasReservationForAccommodation:input_type -> booking.CheckGuestHasReservationForAccommodationRequest
	0,  // 7: booking.BookingService.CheckAccommodationHasReservation:input_type -> booking.CheckAccommodationHasReservationRequest
	13, // 8: booking.BookingService.AddUnavailability:output_type -> booking.AddUnavailabilityResponse
	7,  // 9: booking.BookingService.EditAccommodation:output_type -> booking.EditAccommodationResponse
	15, // 10: booking.BookingService.FilterAvailableAccommodation:output_type -> booking.FilterAvailableAccommodationResponse
	9,  // 11: booking.BookingService.CheckDeleteHost:output_type -> booking.CheckDeleteHostResponse
	11, // 12: booking.BookingService.CheckDeleteClient:output_type -> booking.CheckDeleteClientResponse
	3,  // 13: booking.BookingService.CheckGuestHasReservationForHost:output_type -> booking.CheckGuestHasReservationForHostResponse
	4,  // 14: booking.BookingService.CheckGuestHasReservationForAccommodation:output_type -> booking.CheckGuestHasReservationForAccommodationResponse
	1,  // 15: booking.BookingService.CheckAccommodationHasReservation:output_type -> booking.CheckAccommodationHasReservationResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_booking_service_proto_init() }
func file_booking_service_proto_init() {
	if File_booking_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_booking_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAccommodationHasReservationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAccommodationHasReservationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckGuestHasReservationForHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckGuestHasReservationForHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckGuestHasReservationForAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckGuestHasReservationForAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDeleteHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDeleteHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDeleteClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDeleteClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUnavailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUnavailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterAvailableAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterAvailableAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_booking_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_service_proto_goTypes,
		DependencyIndexes: file_booking_service_proto_depIdxs,
		MessageInfos:      file_booking_service_proto_msgTypes,
	}.Build()
	File_booking_service_proto = out.File
	file_booking_service_proto_rawDesc = nil
	file_booking_service_proto_goTypes = nil
	file_booking_service_proto_depIdxs = nil
}
