// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: booking_service.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccommodationName string `protobuf:"bytes,2,opt,name=accommodation_name,json=accommodationName,proto3" json:"accommodation_name,omitempty"`
	Automatically     bool   `protobuf:"varint,3,opt,name=automatically,proto3" json:"automatically,omitempty"`
}

func (x *EditAccommodationRequest) Reset() {
	*x = EditAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAccommodationRequest) ProtoMessage() {}

func (x *EditAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAccommodationRequest.ProtoReflect.Descriptor instead.
func (*EditAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{0}
}

func (x *EditAccommodationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditAccommodationRequest) GetAccommodationName() string {
	if x != nil {
		return x.AccommodationName
	}
	return ""
}

func (x *EditAccommodationRequest) GetAutomatically() bool {
	if x != nil {
		return x.Automatically
	}
	return false
}

type EditAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditAccommodationResponse) Reset() {
	*x = EditAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAccommodationResponse) ProtoMessage() {}

func (x *EditAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAccommodationResponse.ProtoReflect.Descriptor instead.
func (*EditAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{1}
}

type AddUnavailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccommodationName string `protobuf:"bytes,2,opt,name=accommodation_name,json=accommodationName,proto3" json:"accommodation_name,omitempty"`
	Automatically     bool   `protobuf:"varint,3,opt,name=automatically,proto3" json:"automatically,omitempty"`
}

func (x *AddUnavailabilityRequest) Reset() {
	*x = AddUnavailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUnavailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUnavailabilityRequest) ProtoMessage() {}

func (x *AddUnavailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUnavailabilityRequest.ProtoReflect.Descriptor instead.
func (*AddUnavailabilityRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddUnavailabilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddUnavailabilityRequest) GetAccommodationName() string {
	if x != nil {
		return x.AccommodationName
	}
	return ""
}

func (x *AddUnavailabilityRequest) GetAutomatically() bool {
	if x != nil {
		return x.Automatically
	}
	return false
}

type AddUnavailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddUnavailabilityResponse) Reset() {
	*x = AddUnavailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUnavailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUnavailabilityResponse) ProtoMessage() {}

func (x *AddUnavailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUnavailabilityResponse.ProtoReflect.Descriptor instead.
func (*AddUnavailabilityResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{3}
}

type FilterAvailableAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationIds []string `protobuf:"bytes,1,rep,name=accommodationIds,proto3" json:"accommodationIds,omitempty"`
	StartDate        string   `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate          string   `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *FilterAvailableAccommodationRequest) Reset() {
	*x = FilterAvailableAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterAvailableAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAvailableAccommodationRequest) ProtoMessage() {}

func (x *FilterAvailableAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAvailableAccommodationRequest.ProtoReflect.Descriptor instead.
func (*FilterAvailableAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{4}
}

func (x *FilterAvailableAccommodationRequest) GetAccommodationIds() []string {
	if x != nil {
		return x.AccommodationIds
	}
	return nil
}

func (x *FilterAvailableAccommodationRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *FilterAvailableAccommodationRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type FilterAvailableAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationIds []string `protobuf:"bytes,1,rep,name=accommodationIds,proto3" json:"accommodationIds,omitempty"`
}

func (x *FilterAvailableAccommodationResponse) Reset() {
	*x = FilterAvailableAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterAvailableAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAvailableAccommodationResponse) ProtoMessage() {}

func (x *FilterAvailableAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAvailableAccommodationResponse.ProtoReflect.Descriptor instead.
func (*FilterAvailableAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_rawDescGZIP(), []int{5}
}

func (x *FilterAvailableAccommodationResponse) GetAccommodationIds() []string {
	if x != nil {
		return x.AccommodationIds
	}
	return nil
}

var File_booking_service_proto protoreflect.FileDescriptor

var file_booking_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x22, 0x7f, 0x0a, 0x18, 0x45, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61,
	0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x6c,
	0x79, 0x22, 0x1b, 0x0a, 0x19, 0x45, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7f,
	0x0a, 0x18, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x63,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74,
	0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x22,
	0x1b, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x89, 0x01, 0x0a,
	0x23, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x52, 0x0a, 0x24, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x61, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x32, 0xcb, 0x02, 0x0a,
	0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5c, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x41,
	0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a,
	0x11, 0x45, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x64, 0x69,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x45, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7d, 0x0a, 0x1c, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_booking_service_proto_rawDescOnce sync.Once
	file_booking_service_proto_rawDescData = file_booking_service_proto_rawDesc
)

func file_booking_service_proto_rawDescGZIP() []byte {
	file_booking_service_proto_rawDescOnce.Do(func() {
		file_booking_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_booking_service_proto_rawDescData)
	})
	return file_booking_service_proto_rawDescData
}

var file_booking_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_booking_service_proto_goTypes = []interface{}{
	(*EditAccommodationRequest)(nil),             // 0: booking.EditAccommodationRequest
	(*EditAccommodationResponse)(nil),            // 1: booking.EditAccommodationResponse
	(*AddUnavailabilityRequest)(nil),             // 2: booking.AddUnavailabilityRequest
	(*AddUnavailabilityResponse)(nil),            // 3: booking.AddUnavailabilityResponse
	(*FilterAvailableAccommodationRequest)(nil),  // 4: booking.FilterAvailableAccommodationRequest
	(*FilterAvailableAccommodationResponse)(nil), // 5: booking.FilterAvailableAccommodationResponse
}
var file_booking_service_proto_depIdxs = []int32{
	2, // 0: booking.BookingService.AddUnavailability:input_type -> booking.AddUnavailabilityRequest
	0, // 1: booking.BookingService.EditAccommodation:input_type -> booking.EditAccommodationRequest
	4, // 2: booking.BookingService.FilterAvailableAccommodation:input_type -> booking.FilterAvailableAccommodationRequest
	3, // 3: booking.BookingService.AddUnavailability:output_type -> booking.AddUnavailabilityResponse
	1, // 4: booking.BookingService.EditAccommodation:output_type -> booking.EditAccommodationResponse
	5, // 5: booking.BookingService.FilterAvailableAccommodation:output_type -> booking.FilterAvailableAccommodationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_booking_service_proto_init() }
func file_booking_service_proto_init() {
	if File_booking_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_booking_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUnavailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUnavailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterAvailableAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterAvailableAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_booking_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_service_proto_goTypes,
		DependencyIndexes: file_booking_service_proto_depIdxs,
		MessageInfos:      file_booking_service_proto_msgTypes,
	}.Build()
	File_booking_service_proto = out.File
	file_booking_service_proto_rawDesc = nil
	file_booking_service_proto_goTypes = nil
	file_booking_service_proto_depIdxs = nil
}
