apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: backend
  name: booking
spec:	
  selector:
    matchLabels:
       app: booking
  rules:
    - to:
        - operation:
            methods: [ "GET" ]
            paths: [ "/booking/health" ]
    - to:
        - operation:
            methods: [ "GET", "POST", "PUT", "DELETE" ]
            paths: [ "/booking.BookingService/*" ]
    - to:
        - operation:
            methods: [ "GET" ]
            paths: [ "/booking/unavailability", "/booking/unavailability/accommodation/*" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "host", "guest" ]
    - to:
        - operation:
            methods: [ "GET", "PUT" ]
            paths: [ "/booking/unavailability/host/*", "/booking/unavailability/remove", "/booking/unavailability/add" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "host" ]
    - to:
        - operation:
            methods: [ "POST"]
            paths: [ "/booking/request" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "guest" ]
    - to:
        - operation:
            methods: [ "PUT" ]
            paths: [ "/booking/reservation/decline/*" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "guest" ]
    - to:
        - operation:
            methods: [ "GET" ]
            paths: [ "/booking/request/user/*", "/booking/request/all/*" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "guest", "host" ]
    - to:
        - operation:
            methods: [ "PUT" ]
            paths: [ "/booking/request/approve/*" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "host" ]
    - to:
        - operation:
            methods: [ "PUT" ]
            paths: [ "/booking/request/decline/*" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "guest", "host" ]