apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: booking-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - booking-gateway
  http:
    - match:
        - uri:
            prefix: "/booking"
      route:
        - destination:
            host: booking.default.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: booking-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: booking
        protocol: HTTP
      hosts:
        - "*"